In [2]:
import numpy as np

In [2]:
np.array(['vamsi'])

array(['vamsi'], dtype='<U5')

In [4]:
np.array(['vamsi'],dtype=str)

array(['vamsi'], dtype='<U5')

In [35]:
arr = np.genfromtxt('speeches.txt',dtype=str,autostrip=True,invalid_raise = False,max_rows = 100)

D:\Work\Anaconda\lib\site-packages\ipykernel_launcher.py:1: ConversionWarning: Some errors were detected !
    Line #2 (got 63 columns instead of 24)
    Line #3 (got 43 columns instead of 24)
    Line #4 (got 50 columns instead of 24)
    Line #5 (got 41 columns instead of 24)
    Line #6 (got 27 columns instead of 24)
  """Entry point for launching an IPython kernel.


In [36]:
len(arr)

24

In [1]:
x = ['this','is','it']

In [4]:
np.array(x)

array(['this', 'is', 'it'], dtype='<U4')

In [47]:
file = open('speeches.txt','r')

In [48]:
file.readline()

'* Valid only at participating locations; while supplies last; batteries not included; objects in mirror may be closer than they appear; other necessary disclaimers. \n'

In [49]:
s = file.read()

In [50]:
s


'Inspired by Mark Obmascik\'s nonfiction book, David Frankel\'s film observes the migratory patterns of three breeds of birders. Do they criss-cross the country from Alaska\'s Aleutians to Florida\'s Everglades because they feel trapped by their lives? Or because by observing avian life they better understand humans? Yes and maybe, suggests this gently eccentric film from Frankel (The Devil Wears Prada, Marley & Me).\nParker frames her tale as a love story between her great-aunt Mary and her husband, Thomas Henry Davison. She spices the story with an intriguing family heirloom -- the skirt Davison wore as she climbed into the lifeboat that took her to safety.\nThey might have been tempted to quit when Andy Pettitte brushed back the government\'s case against Roger Clemens with a high, hard one out of nowhere. Could have just bagged it all about the time one juror fell asleep, and another wondered just what Clemens was on trial for anyway.\nCassady, the inspiration for Dean Moriarty in 

In [51]:
file.close()

In [52]:
s

'Inspired by Mark Obmascik\'s nonfiction book, David Frankel\'s film observes the migratory patterns of three breeds of birders. Do they criss-cross the country from Alaska\'s Aleutians to Florida\'s Everglades because they feel trapped by their lives? Or because by observing avian life they better understand humans? Yes and maybe, suggests this gently eccentric film from Frankel (The Devil Wears Prada, Marley & Me).\nParker frames her tale as a love story between her great-aunt Mary and her husband, Thomas Henry Davison. She spices the story with an intriguing family heirloom -- the skirt Davison wore as she climbed into the lifeboat that took her to safety.\nThey might have been tempted to quit when Andy Pettitte brushed back the government\'s case against Roger Clemens with a high, hard one out of nowhere. Could have just bagged it all about the time one juror fell asleep, and another wondered just what Clemens was on trial for anyway.\nCassady, the inspiration for Dean Moriarty in 

In [66]:
tobe = [';','.' , '\\' , '\n','\"','-','?','(',')','!','*','&','']

In [67]:
tobe

[';', '.', '\\', '\n', '"', '-', '?', '(', ')', '!', '*', '&', '']

In [56]:
s = s.strip()

In [57]:
arr = s.split(' ')

In [58]:
mystr = s

In [41]:
unique_elements, counts_elements = np.unique(arr, return_counts=True)

In [42]:
unique_elements

array(['', "Alaska's", 'Aleutians', 'Andy', 'Chen', 'China,', 'Clemens',
       'Could', 'David', 'Davison', 'Dean', 'Devil', 'Do', 'Everglades',
       "Florida's", 'Frankel', "Frankel's", 'Help', 'Henry', 'Inspired',
       "It's", 'Jack', "Kerouac's", 'Mark', 'Marley', 'Mary', 'MeParker',
       'Merry', 'Moriarty', "Obmascik's", 'On', 'Or', 'Pettitte',
       'Prada,', "Pranksters'", 'Road,', 'Roger', 'She', 'The', 'Thomas',
       'Washington', 'Wears', 'Yes', 'a', 'about', 'actually', 'again',
       'against', 'all', 'an', 'and', 'another', 'anywayCassady,',
       'appealing', 'as', 'asleep,', 'avian', 'back', 'bagged', 'beatnik',
       'because', 'been', 'behind', 'better', 'between', 'birders',
       'book,', 'breeds', 'brushed', 'by', 'case', 'climbed', 'comes',
       'country', 'crisscross', 'designated', 'driverI', 'eccentric',
       'especially', 'family', 'feel', 'fell', 'film', 'for', 'frames',
       'from', 'gently', "government's", 'greataunt', 'hard', 'have',
  

In [43]:
counts_elements

array([ 3,  1,  1,  1,  1,  1,  2,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,  4,
        1,  1,  1,  3,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  2,  4,  1,
        3,  1,  1,  1,  1,  2,  1,  1,  4,  1,  1,  1,  2,  1,  1,  1,  1,
        1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  5,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  2,  1,  1,  1,  2, 12,  1,  3,  2,  2,  1,  1,  5,  1,
        1,  1,  1,  1,  2,  1,  1,  1,  1,  2,  1,  1], dtype=int64)

In [70]:
file = open('speeches.txt','r')

In [71]:
mystr = file.read()

In [72]:
for x in tobe:
   mystr = mystr.replace(x,'')

In [73]:
mystr = mystr.split(' ')

In [74]:
mystr = np.array(mystr)

In [75]:
uniq , count = np.unique(mystr,return_counts=True)

In [76]:
uniq

array(['', "Alaska's", 'Aleutians', 'Andy', 'Chen', 'China,', 'Clemens',
       'Could', 'David', 'Davison', 'Dean', 'Devil', 'Do', 'Everglades',
       "Florida's", 'Frankel', "Frankel's", 'Help', 'Henry', 'Inspired',
       "It's", 'Jack', "Kerouac's", 'Mark', 'Marley', 'Mary', 'MeParker',
       'Merry', 'Moriarty', "Obmascik's", 'On', 'Or', 'Pettitte',
       'Prada,', "Pranksters'", 'Road,', 'Roger', 'She', 'The', 'Thomas',
       'Valid', 'Washington', 'Wears', 'Yes', 'a', 'about', 'actually',
       'again', 'against', 'all', 'an', 'and', 'another',
       'anywayCassady,', 'appealing', 'appear', 'as', 'asleep,', 'at',
       'avian', 'back', 'bagged', 'batteries', 'be', 'beatnik', 'because',
       'been', 'behind', 'better', 'between', 'birders', 'book,',
       'breeds', 'brushed', 'by', 'case', 'climbed', 'closer', 'comes',
       'country', 'crisscross', 'designated', 'disclaimers', 'driverI',
       'eccentric', 'especially', 'family', 'feel', 'fell', 'film', 'for',
      

In [77]:
count

array([ 4,  1,  1,  1,  1,  1,  2,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,
        4,  1,  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,
        1,  1,  1,  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  2,  1,  1,  2,  4,  1,  3,  1,  1,  1,  1,  2,  1,  1,  4,  1,
        1,  1,  3,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  5,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  2, 12,  1,  4,  2,  2,  1,
        1,  5,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  2,  1,  1],
      dtype=int64)

In [78]:
matrix = np.zeros((len(uniq),len(uniq)))

In [79]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [80]:
def feedProb(mystr,i,j,uniq,count):
    j_count = 0
    target = uniq[j]
#     print(uniq[7])
    
    x = np.where(uniq[i] == mystr)

    x = np.array(x)
    x = x.flatten()
    x += 1
    mask = x <= len(mystr) - 1
    x = x[mask]

    if x.size != 0:
        tar = target == mystr[x]
    
    else:
        tar = np.array([])
    k = tar == True    
   
    for z in k:
        if(z == True):
            j_count += 1
    


    return j_count / count[i]
#     return 

In [81]:
def createMatrix(matrix,uniq,count,mystr):
    for r in range(len(uniq)):
        for k in range(len(uniq)):
            matrix[r,k] = feedProb(mystr,r,k,uniq,count)
    return matrix

In [82]:
createMatrix(matrix,uniq,count,mystr)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
len(uniq)

3

In [86]:
for i in range(15):
    print(np.random.choice(uniq,1,p=matrix[i,:]))

['the']
['Aleutians']
['to']
['Pettitte']
['said,']
['Chen']
['was']
['have']
["Frankel's"]
['wore']
['Moriarty']
['Wears']
['they']
['because']
['Everglades']
