In [1]:
import numpy as np

In [2]:
from matplotlib import pyplot as plt

In [48]:
class gradientDescent:
    
    
    def __init__(self,lr):
        
        self.weights = 2*np.random.rand(3) - 1
        self.lr = lr
        self.tol = 0.000000001
        
        self.data = np.genfromtxt('logistic.txt',delimiter='')
        padding = np.ones((len(self.data)))
        
        temp = self.data[:,2]
        temp = np.c_[temp]
        self.data[:,2] = padding
        
        
        self.data = np.hstack([self.data,temp])
        
        self.activation = lambda x : 1/(1+np.exp(-x))
        
        
    def differ_p(self,ws):
        
        loss = 0
        
        for pt in self.data:
            
            zk = pt[3] * (ws[0]*pt[0] + ws[1]*pt[1] + ws[2])
            loss += (1 - self.activation(zk))*pt[3]*pt[:3]
        
        
        return loss
        
        
        
    def runDescent(self):
        
        diff = self.differ_p(self.weights)
        
        stepsize_w = self.lr * diff
       
        
        while np.all(abs(stepsize_w) > self.tol):
        
        
            if(abs(stepsize_w[0]) > self.tol):                
                self.weights[0] -= stepsize_w[0]
                
            if(abs(stepsize_w[1]) > self.tol):
                self.weights[1] -= stepsize_w[1]
                
        
            if(abs(stepsize_w[2]) > self.tol):
                self.weights[2] -= stepsize_w[2]
        
            
            diff = self.differ_p(self.weights)
        
            stepsize_w = self.lr * diff
            
            print(self.weights)
            
            
  
    def plotpoints(self):  
    
        
        plt.plot(self.data[:,0],self.data[:,1],'o')
        
        
        x = np.linspace(-1,1,100)
        
        
        y = -(self.weights[2] + self.weights[0]*x)/self.weights[1]
        
        plt.plot(x,y)
    
    
    
    
    

In [49]:
opt = gradientDescent(0.01)

In [50]:
opt.runDescent()

[-0.14045146  0.08214742  0.95187788]
[-2.18640102e-01 -8.24209437e-04  9.95176498e-01]
[-0.30483178 -0.09247607  1.03633695]
[-0.40047175 -0.19440556  1.07433738]
[-0.5071642  -0.30839865  1.10800892]
[-0.62646674 -0.43621196  1.13615997]
[-0.75949873 -0.57914567  1.15782467]
[-0.90643895 -0.73747849  1.17259987]
[-1.06619663 -0.91007332  1.18089703]
[-1.2365775  -1.09452932  1.18388515]
[-1.41491371 -1.28787717  1.18310719]
[-1.59873703 -1.4873498   1.18002862]
[-1.78614097 -1.69080703  1.17577335]
[-1.97581631 -1.8967827   1.17108208]
[-2.16692529 -2.10434285  1.16638942]
[-2.35895102 -2.31291434  1.16192419]
[-2.55157848 -2.52214966  1.15779026]
[-2.74461472 -2.73183691  1.15402092]
[-2.93793954 -2.94184433  1.15061207]
[-3.13147597 -3.15208762  1.14754141]
[-3.32517313 -3.36251082  1.14477911]
[-3.51899607 -3.57307531  1.14229349]
[-3.71291989 -3.78375336  1.14005389]
[-3.9069262  -3.99452432  1.13803204]
[-4.10100101 -4.2053723   1.13620253]
[-4.29513335 -4.4162848   1.13454287]


In [51]:
opt.plotpoints()